### ISSUE TITLE
v1.6.0 does not create CRD auto

### ISSUE THREAD

**Issue by zorrofox** [StarRocks/helm-charts#29]
The HELM deployment will failed due to v1.6.0 does not create CRD auto.

**Comment by shileifu** [comment]
helm will not auto-update crd, please manual update crd.

**Comment by zorrofox** [comment]
Fresh install will failed into this
```bash
% helm install starrocks starrocks-community/kube-starrocks

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "kube-starrocks" namespace: "default" from "": no matches for kind "StarRocksCluster" in version "starrocks.com/v1}"
```

**Comment by zorrofox** [comment]
> Fresh install will failed into this
> 
> ```shell
> % helm install starrocks starrocks-community/kube-starrocks
> 
> Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "kube-starrocks" namespace: "default" from "": no matches for kind "StarRocksCluster" in version "starrocks.com/v1}"
> ```

I think [this line](https://github.com/StarRocks/helm-charts/blob/82df7b3567550bf6d93bb83a6cf1a2ae3d4e7e0b/charts/kube-starrocks/templates/starrocks/starrockscluster.yaml#L1) has one more bracket:
```
apiVersion: starrocks.com/{{ .Values.global.crdVersion }}}
```
It should be:
```
apiVersion: starrocks.com/{{ .Values.global.crdVersion }}
```

**Comment by shileifu** [comment]
done, update to v1.6.1
