### ISSUE TITLE
【help】生产推荐哪种方案呢？

### ISSUE THREAD

**Issue by zyclove** [StarRocks/helm-charts#36]
![image](https://github.com/StarRocks/helm-charts/assets/15028279/c07d707f-40f0-4cc6-ae8f-81f24d55eedc)

请问现在还存在哪些问题呢？

https://docs.starrocks.io/en-us/3.0/deployment/sr_operator
这个方案可以生产部署吗？

该项目也是一样架构吧？
![image](https://github.com/StarRocks/helm-charts/assets/15028279/bcee1efe-c532-45f9-ad05-c6adf00aecbf)

**Comment by kevincai** [comment]
helm可能涉及到的问题有:
* CRD upgrade
* multiple operators deployed by mistake due to multiple charts deployed

如果对helm以及crd有比较深入的了解, 在生产环境使用helm也是可以的.
